/**
 * Spanish (es) translations for the Don't Starve Food Guide UI.
 *
 * Translation provenance: initial pass generated by Anthropic Claude Opus
 * (model id `claude-opus-4.7`) and not yet reviewed by a native-speaking
 * Don't Starve player. Treat strings as a starting point — corrections
 * via PR are welcome.
 *
 * Names of foods, recipes, characters, and DLCs are intentionally left
 * untranslated for now: those should be sourced from the game itself.
 */

import { registerLocale } from '../strings.js';

/** @type {import('../strings.js').LocaleDict | Record<string, string>} */
const dict = {
	themeToggleTitle: 'Cambiar tema claro/oscuro',

	languagePickerLabel: 'Idioma',
	languagePickerTitle: 'Cambiar idioma',
	languageNote:
		'Las traducciones fueron generadas por Anthropic Claude Opus y pueden requerir revisión de la comunidad.',

	modeLabelGame: 'Juego',
	modeLabelDlc: 'DLC',
	modeLabelCharacter: 'Pers.',
	dlcToggleHint: 'haz clic para alternar',
	characterToggleHint: 'haz clic para alternar',

	abilityNoMonsterPenalty: 'Puede comer Comida de Monstruo sin riesgo',
	abilityRawMeatIsCooked: 'Puede comer Carne Cruda sin riesgo',
	abilityMeatOnly: 'Solo come carne',
	abilityMeatAndGoodies: 'Solo come carne y golosinas',

	tabSimulator: 'Simulador',
	tabSimulatorTitle: 'Simulación de recetas de la Olla',
	tabDiscovery: 'Descubrimiento',
	tabDiscoveryTitle: 'Añade objetos del inventario para encontrar recetas',
	tabFoodList: 'Lista de comida',
	tabFoodListTitle: 'Ver toda la comida del DLC seleccionado',
	tabRecipeList: 'Lista de recetas',
	tabRecipeListTitle: 'Ver todas las recetas del DLC seleccionado',
	tabStatistics: 'Analizador de estadísticas',
	tabStatisticsTitle: 'Encuentra todas las recetas (inestable)',
	tabAbout: 'Acerca de',
	tabAboutTitle: 'Acerca de esta herramienta y cómo usarla',
	tabGameInfo: 'Info del juego',
	tabGameInfoTitle: "Referencia de las mecánicas de Don't Starve",

	noscriptMessage: 'Lo sentimos, esta Guía de Comida requiere JavaScript y un navegador moderno.',
	simulatorHeading: 'Simulador de Olla',
	simulatorBody:
		'Busca ingredientes abajo, luego haz clic para añadirlos a la olla. Haz clic en una ranura para quitar un ingrediente.',
	discoveryHeading: 'Descubrimiento de Inventario',
	discoveryBody:
		'Añade abajo todos los objetos de tu inventario para ver qué recetas puedes preparar. Haz clic en + para añadir más.',
	discoveryFoodStatsHeading: 'Estadísticas de tu comida:',
	discoveryRecipesHeading: 'Con esto, puedes preparar:',
	discoveryEfficientHeading: 'Encuentra qué recetas son más eficientes:',
	discoveryHighlightsNote: 'La(s) fila(s) resaltada(s) se seleccionarán al cocinar.',
	discoveryMoreSuggestions: 'Añade más ingredientes para preparar:',
	simulatorSelectedIngredients: 'Ingredientes seleccionados para la Olla',
	discoverySelectedIngredients: 'Comida disponible',
	searchIngredientsPlaceholder: 'Buscar ingredientes...',

	clearSearchOrIngredients: 'Borrar búsqueda o quitar todos los ingredientes',
	confirmClearInventory: '¿Seguro que quieres quitar todos los ingredientes de tu inventario?',
	displayModeNames: 'Mostrar: Nombres',
	displayModeIcons: 'Mostrar: Iconos',
	displayModeList: 'Mostrar: Lista',
	densityCozy: 'Cómodo',
	densityNormal: 'Normal',
	densityCompact: 'Compacto',
	sortDefault: 'Orden: Predeterminado',
	sortName: 'Orden: Nombre',
	sortHealth: 'Orden: Salud',
	sortHunger: 'Orden: Hambre',
	sortSanity: 'Orden: Cordura',
	sortPerish: 'Orden: Caducidad',
	searchTypeName: 'nombre',
	searchTypeTag: 'etiqueta',
	searchTypeRecipe: 'receta',
	searchPlaceholderName: 'Filtrar ingredientes',
	searchPlaceholderTag: 'Carne, verdura, fruta, huevo, monstruo...',
	searchPlaceholderRecipe: 'Buscar ingredientes usados en una receta',

	calculateRecipes: 'Calcular recetas eficientes (puede tardar)',
	clearResults: 'Limpiar resultados',
	calculating: 'Calculando...',
	pause: 'Pausar',
	resume: 'Reanudar',
	computingCombinations: 'Calculando combinaciones..',
	multipleResultsNote: '* la combinación tiene varios resultados posibles',
	filterCycleHelp:
		'Haz clic en ingredientes/recetas para alternar: normal → requerido (✓) → excluido (✕). Clic derecho para excluir rápido.',
	customFilterPlaceholder: 'usar filtro personalizado',
	foundValidRecipes: 'Se encontraron {count} recetas válidas.',
	foundValidRecipesInProgress:
		'Se encontraron {count} recetas válidas.. (puedes cambiar de pestaña durante este proceso)',
	foundValidRecipesPaused: 'Se encontraron {count} recetas válidas (en pausa)',
	showMoreResults: 'Mostrar más resultados',
	showMoreResultsCount: 'Mostrar más resultados ({shown} de {total})',
	durationNever: 'Nunca',
	durationDays: '{count} {unit}',
	durationSeconds: '{count} {unit}',
	durationToNever: 'a Nunca',
	durationToDays: 'a {count} {unit}',
	simulatorSummaryTotal: 'Total',
	simulatorSummaryPotential: 'Potencial',
	foodInfoRecipes: 'Recetas',
	foodInfoFrom: 'de',
	foodInfoCook: 'cocinar',
	foodInfoDryIn: 'se seca en {duration}',
	foodInfoCannotAdd: 'no se puede añadir a la Olla',
	noteProvidesHeatFor: 'Proporciona {heat} de calor durante {duration}',
	noteHeatWhenConsumed: 'Aporta {heat} de calor al consumirse',
	noteLightSeconds: 'Da {seconds} segundos de luz',
	noteSpeedBonusForSeconds:
		'Da {speed} de velocidad adicional ({percent}) durante {seconds} segundos',
	noteDriesRateForSeconds: 'Seca {rate} durante {seconds} segundos',
	noteHeatDelta: '{heat} de calor',
	noteGlowDarkMinutes: 'Hace que el jugador brille en la oscuridad durante {minutes} minutos',
	notePreventsHayfeverSeconds: 'Evita la fiebre del heno durante {seconds} segundos',
	notePoisonous: 'Venenoso',
	noteCuresPoison: 'Cura el veneno',
	notePutsPlayerToSleep: 'Duerme al jugador',
	noteRemovesGrogginessEffect: 'Elimina el efecto de aturdimiento',
	noteGivesNaughtiness: 'Da {amount} de travesura',
	noteSpeedBonusForSecondsDays:
		'Da {speed} de velocidad adicional ({percent}) durante {seconds} segundos ({days} días)',
	noteHayfeverSecondsDays: 'Evita la fiebre del heno durante {seconds} segundos ({days} días)',
	noteProducesAndHealsOverMinutes:
		'La receta produce {count}; cura {health} de salud en {minutes} minutos',
	noteIncreasesTemperatureByDegreesInSeconds:
		'Aumenta la temperatura en {degrees} grados en {seconds} segundos.',
	noteRestoresSanityOverMinutes: 'Restaura {sanity} de cordura en {minutes} minuto',
	noteLowersTemperatureByDegreesOverSeconds:
		'Baja la temperatura {degrees} grados en {seconds} segundos',
	noteRaisesTemperatureByDegreesOverSeconds:
		'Sube la temperatura {degrees} grados en {seconds} segundos',
	noteRequiresUncookedTallbirdEgg: 'Requiere Huevo de Tallbird sin cocinar',
	notePlayerCannotEatBeefaloOnly: 'No puede comerlo el jugador; solo puede darse a los Beefalo',
	noteDustMothsOnly: 'Se usa para alimentar a las Dust Moths; el jugador no puede comerlo',
	notes: {
		'Removes 3 heat, and for 30 seconds, dries 1/s and adds 2 bonus speed (+33%)':
			'Quita 3 de calor y, durante 30 segundos, seca 1/s y añade 2 de velocidad adicional (+33%)',
		'While worn, restores 3.9 Hunger every 5 seconds (187.5 in total, over 4 minutes), while reducing Sanity by 1.33 per minute (Wurt gains +1.33 sanity/min, Wigfrid refuses to wear this)':
			'Mientras se lleva puesto, restaura 3.9 de Hambre cada 5 segundos (187.5 en total, durante 4 minutos), mientras reduce la Cordura en 1.33 por minuto (Wurt gana +1.33 cordura/min, Wigfrid se niega a llevarlo)',
		'Gives those that eat this 16 minutes of light that fades in a similar fashion after eating a glowberry':
			'Da a quien lo come 16 minutos de luz que se desvanece de forma similar a la de comer una glowberry',
	},

	columns: 'Columnas',
	autoColumns: 'Auto',
	autoColumnsTitle:
		'Ocultar automáticamente las columnas menos importantes en pantallas estrechas',
	tableName: 'Nombre',
	tableInfo: 'Info',
	tableMode: 'Modo',
	tableHealth: 'Salud',
	tableHealthGain: 'Salud+',
	tableHunger: 'Hambre',
	tableHungerGain: 'Hambre+',
	tableSanity: 'Cordura',
	tablePerish: 'Caducidad',
	tableCookTime: 'Tiempo de cocción',
	tablePriority: 'Prioridad',
	tableNotes: 'Notas',
	tableRequires: 'Requiere',
	tableIngredients: 'Ingredientes',
	tableHealthHint: 'Salud restaurada (cambia al cocinar)',
	tableHungerHint: 'Hambre restaurada (cambia al cocinar)',
	tableSanityHint: 'Cordura restaurada (cambia al cocinar)',
	tablePerishHint: 'Tiempo hasta convertirse en podredumbre (cambia al cocinar)',
	tablePriorityHint: 'Se preparará una de las recetas de mayor prioridad para una combinación',
	tableRequiresHint: 'Los elementos atenuados o tachados no pueden usarse',
	tableModeHint: 'DLC o modo de juego requerido',
	tableHealthGainHint: 'Salud ganada en comparación con los ingredientes',
	tableHungerGainHint: 'Hambre ganada en comparación con los ingredientes',

	aboutHeading: 'Acerca de esta Guía de Comida',
	aboutIntro:
		'Esta es una herramienta no oficial para evitar morir de hambre en <a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a>, un implacable juego de supervivencia salvaje lleno de ciencia y magia hecho por <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a>.',
	aboutBrowser:
		'Esta página requiere un navegador moderno (versión reciente de Firefox, Chrome, Edge o Safari) y se ejecuta localmente con JavaScript.',
	aboutSource:
		'Código abierto, mantenido como esfuerzo comunitario en GitHub: <a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">github.com/bluehexagons/foodguide</a>.',
	aboutChangelog:
		'Para ver los cambios más recientes, consulta el <a href="https://github.com/bluehexagons/foodguide/commits/main" target="_blank" rel="noopener">historial de commits</a>.',
	aboutSectionsHeading: 'Secciones',
	aboutSimulatorHeading: 'Simulador',
	aboutSimulatorBody:
		'El Simulador funciona como una Olla: añade objetos y te dirá qué comida se preparará. Solo las recetas de mayor prioridad podrán salir al cocinar realmente en el juego. Los totales combinados arriba reflejan los ingredientes añadidos, donde el tiempo de caducidad es el más corto. Las sugerencias debajo de los resultados reales muestran qué recetas podrías preparar añadiendo otros ingredientes a los que ya hay en la Olla.',
	aboutDiscoveryHeading: 'Descubrimiento',
	aboutDiscoveryBody:
		'La pestaña Descubrimiento encuentra qué recetas pueden prepararse con un conjunto de ingredientes. No tiene en cuenta la cantidad de cada uno; asume que tienes cuatro de cada. También puedes calcular las recetas más eficientes con tus ingredientes para sacar el máximo provecho de salud o hambre al cocinarlos. Funciona igual que la pestaña Analizador de Estadísticas, pero limitado a tu inventario.',
	aboutFoodRecipeListsHeading: 'Lista de Comida y Lista de Recetas',
	aboutFoodRecipeListsBody:
		"Explora todas las comidas y recetas de Olla disponibles en la versión de juego seleccionada. Usa el selector de versión arriba a la izquierda para cambiar entre Don't Starve Together, Don't Starve y Hamlet.",
	aboutStatisticsHeading: 'Analizador de Estadísticas',
	aboutStatisticsBody:
		'La pestaña Analizador de Estadísticas es para quienes quieren explorar combinaciones de ingredientes. Calcula todas las combinaciones válidas posibles (con una selección "ideal", excluyendo en general la comida cruda) y permite filtrar por contenido de recetas e ingredientes. El cálculo puede tardar en computadoras lentas.',
	aboutAdvancedHeading: 'Uso avanzado (variables globales de JavaScript)',
	aboutAdvancedBody1:
		'La Guía de Comida añade a <code>window</code> algunas propiedades: <code>food</code>, <code>recipes</code> y <code>matchingNames</code>. El Analizador de Estadísticas escribe sus resultados en <code>analysis</code> y <code>recipeCrunchData</code>. El estado local se guarda en <code>localStorage.foodGuideState</code>.',
	aboutAdvancedBody2:
		'Para uso avanzado, abre la consola JavaScript del navegador. <code>analysis.made</code> contiene la lista de combinaciones válidas del último análisis, incluyendo las que no se ven en la interfaz.',
	aboutLinksHeading: 'Enlaces',
	linkChangelog: 'Registro de cambios de la Guía',
	linkBugReports: 'Reportar errores / problemas de la Guía',
	linkOfficialSite: "Sitio oficial de Don't Starve",
	linkWiki: "Wiki de Don't Starve",

	gameInfoFoodMechHeading: 'Mecánicas de Comida',
	gameInfoFoodMechBody:
		'El <strong>tiempo de caducidad</strong> es el tiempo antes de que la comida se convierta en <strong>Podredumbre</strong>. A la <strong>mitad</strong> de ese tiempo, se vuelve <strong>rancia</strong>, y aporta <strong><span id="stalehealth"></span> de salud</strong> y <strong><span id="stalehunger"></span> de hambre</strong>, sin <strong>cordura</strong>. La comida se <strong>echa a perder</strong> a los <strong>tres cuartos</strong>, dando solo <strong><span id="spoiledhunger"></span> de hambre</strong> y <strong>ya no aporta salud</strong>. Comer comida echada a perder reduce la cordura en <strong><span id="spoiledsanity"></span></strong>. La comida <strong>tirada al suelo</strong> <strong>caduca</strong> a una tasa de <strong><span id="perishground"></span></strong> (o <strong><span id="perishwinter"></span></strong> en <strong>Invierno</strong>, <strong><span id="perishsummer"></span></strong> en <strong>Verano</strong>); guardarla en la <strong>Nevera</strong> reduce la tasa a <strong><span id="perishfridge"></span></strong>.',
	gameInfoWarmth:
		'Las comidas que dan <strong>calor</strong> o <strong>frescor</strong> funcionan como una piedra térmica: al comerlas, proporcionan una fuente de calor a cierta temperatura durante un tiempo. Comer otro alimento que caliente o enfríe durante ese periodo reemplaza el efecto anterior.',
	gameInfoPriority:
		'La <strong>prioridad de receta</strong> determina qué receta producirá una combinación de ingredientes; solo pueden prepararse las recetas posibles de mayor prioridad para una tanda de ingredientes.',
	gameInfoCooked:
		'En los requisitos de receta, normalmente da igual si el ingrediente está cocinado o no. Cuando importa, solo se indica la forma válida.',
	gameInfoVersionsHeading: 'Versiones del juego y DLC',
	gameInfoVersionsBody:
		"El selector de versión arriba a la izquierda permite cambiar entre Don't Starve Together (DST), Don't Starve (DS) y Hamlet. Con Don't Starve seleccionado, puedes activar o desactivar los DLC Reign of Giants y Shipwrecked para controlar qué comidas y recetas se muestran. También puedes elegir un personaje como Warly o Webber para ver sus recetas y mecánicas especiales.",
	gameInfoCharactersHeading: 'Mecánicas de comida por personaje',
	gameInfoWarly:
		'<strong>Warly</strong> es un personaje chef que solo puede jugarse en Shipwrecked, Hamlet y DST. En Shipwrecked, sus comidas son más saciantes preparadas como recetas pero menos efectivas crudas, secas o cocinadas. También tiene acceso a recetas únicas no disponibles para otros personajes.',
	gameInfoWebber:
		'<strong>Webber</strong> es un híbrido humano-araña jugable en todas las versiones. Puede comer Comida de Monstruo sin efectos negativos, y come Carne Cruda como si estuviera cocinada (con toda la salud y sin penalización de cordura). Es además el único personaje que puede entablar amistad de forma natural con las Arañas.',
	gameInfoWigfrid:
		'<strong>Wigfrid</strong> es un personaje de Reign of Giants disponible en Don\'t Starve Together. Es una intérprete teatral que solo come carne. En Don\'t Starve Together también puede comer "golosinas" como Caramelos, Gominolas y Volt Goat Chaud-Froid.',
	gameInfoFavoritesHeading: 'Comidas favoritas (DST)',
	gameInfoFavoritesBody:
		"En Don't Starve Together, cada personaje gana 15 de Hambre extra al comer su comida favorita. La bonificación se ve afectada por la frescura.",
	favoritesHeaderCharacter: 'Personaje',
	favoritesHeaderFavorite: 'Comida favorita',
	gameInfoWikiHeading: 'Páginas útiles del wiki',
	wikiFood: 'Comida',
	wikiCooking: 'Cocina',
	wikiCrockPot: 'Olla',
	wikiFarming: 'Agricultura',

	footerCopyrightLicense:
		'<a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a> &copy; <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a>. Guía de comida no oficial; <a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">código fuente</a> publicado bajo la <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank" rel="noopener">Apache License 2.0</a>.',
	footerLinks:
		'<a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">Código fuente en GitHub</a> | <a href="https://github.com/bluehexagons/foodguide/issues" target="_blank" rel="noopener">Errores y peticiones</a>',

	// Etiquetas de ingredientes / recetas. Las claves deben coincidir con
	// el diccionario inglés en html/strings.js (y con los identificadores
	// internos de los datos); solo se traduce la etiqueta visible. El
	// prefijo de búsqueda `tag:KEY` permanece en inglés en el enlace
	// subyacente.
	tags: {
		fruit: 'fruta',
		veggie: 'verdura',
		meat: 'carne',
		egg: 'huevo',
		fish: 'pescado',
		magic: 'magia',
		decoration: 'decoración',
		inedible: 'no comestible',
		monster: 'comida de monstruo',
		sweetener: 'edulcorante',
		fat: 'grasa',
		dairy: 'lácteo',
		jellyfish: 'medusa',
		antihistamine: 'antihistamínico',
		filter: 'filtro',
		bug: 'insecto',
		bone: 'hueso',
		roughage: 'fibra',
		goodies: 'golosinas',
		honeyed: 'con miel',
		monstermeat: 'carne de monstruo',
	},
};

registerLocale('es', 'Español', dict);
