/**
 * Simplified Chinese (zh) translations for the Don't Starve Food Guide UI.
 *
 * Translation provenance: initial pass generated by Anthropic Claude Opus
 * (model id `claude-opus-4.7`) and not yet reviewed by a native-speaking
 * Don't Starve player. Treat strings as a starting point — corrections
 * via PR are welcome.
 *
 * Names of foods, recipes, characters, and DLCs are intentionally left
 * untranslated for now: those should be sourced from the game itself.
 */

import { registerLocale } from '../strings.js';

/** @type {import('../strings.js').LocaleDict | Record<string, string>} */
const dict = {
	themeToggleTitle: '切换深色/浅色主题',

	languagePickerLabel: '语言',
	languagePickerTitle: '更改语言',
	languageNote: '翻译由 Anthropic Claude Opus 生成,可能需要社区校对。',

	modeLabelGame: '游戏',
	modeLabelDlc: 'DLC',
	modeLabelCharacter: '角色',
	dlcToggleHint: '点击切换',
	characterToggleHint: '点击切换',

	abilityNoMonsterPenalty: '可安全食用怪物食物',
	abilityRawMeatIsCooked: '可安全食用生肉',
	abilityMeatOnly: '只吃肉类',
	abilityMeatAndGoodies: '只吃肉类和甜食',

	tabSimulator: '模拟器',
	tabSimulatorTitle: '锅炉烹饪模拟',
	tabDiscovery: '发现',
	tabDiscoveryTitle: '添加背包物品以查找配方',
	tabFoodList: '食物列表',
	tabFoodListTitle: '查看所选 DLC 中的全部食物',
	tabRecipeList: '配方列表',
	tabRecipeListTitle: '查看所选 DLC 中的全部配方',
	tabStatistics: '统计分析器',
	tabStatisticsTitle: '查找所有配方(不稳定)',
	tabAbout: '关于',
	tabAboutTitle: '关于本工具及其使用方法',
	tabGameInfo: '游戏信息',
	tabGameInfoTitle: "Don't Starve 游戏机制参考",

	noscriptMessage: '抱歉,本食物指南需要 JavaScript 和现代浏览器。',
	simulatorHeading: '锅炉模拟器',
	simulatorBody: '在下方搜索食材,然后点击它们加入锅中。点击锅中的格子可移除该食材。',
	discoveryHeading: '背包发现',
	discoveryBody: '在下方添加你背包中的所有物品,查看可制作的配方。点击 + 添加更多物品。',
	discoveryFoodStatsHeading: '你的食物统计:',
	discoveryRecipesHeading: '使用这些可以制作:',
	discoveryEfficientHeading: '查找最高效的配方:',
	discoveryHighlightsNote: '高亮行将在烹饪时被选中。',
	discoveryMoreSuggestions: '添加更多食材以制作:',
	simulatorSelectedIngredients: '已选择的锅中食材',
	discoverySelectedIngredients: '现有食物',
	searchIngredientsPlaceholder: '搜索食材...',

	clearSearchOrIngredients: '清除搜索或移除所有食材',
	confirmClearInventory: '确定要从背包中移除所有食材吗?',
	displayModeNames: '显示:名称',
	displayModeIcons: '显示:图标',
	displayModeList: '显示:列表',
	densityCozy: '宽松',
	densityNormal: '标准',
	densityCompact: '紧凑',
	sortDefault: '排序:默认',
	sortName: '排序:名称',
	sortHealth: '排序:生命',
	sortHunger: '排序:饥饿',
	sortSanity: '排序:理智',
	sortPerish: '排序:腐败',
	searchTypeName: '名称',
	searchTypeTag: '标签',
	searchTypeRecipe: '配方',
	searchPlaceholderName: '过滤食材',
	searchPlaceholderTag: '肉、菜、果、蛋、怪物……',
	searchPlaceholderRecipe: '查找配方所用食材',

	calculateRecipes: '计算高效配方(可能耗时)',
	clearResults: '清除结果',
	calculating: '计算中……',
	pause: '暂停',
	resume: '继续',
	computingCombinations: '正在计算组合……',
	multipleResultsNote: '* 该组合有多个可能结果',
	filterCycleHelp: '点击食材/配方循环切换:普通 → 必需(✓) → 排除(✕)。右键可快速排除。',
	customFilterPlaceholder: '使用自定义过滤器',
	foundValidRecipes: '找到 {count} 个有效配方。',
	foundValidRecipesInProgress: '找到 {count} 个有效配方……(此过程中可切换标签页)',
	foundValidRecipesPaused: '找到 {count} 个有效配方(已暂停)',
	showMoreResults: '显示更多结果',
	showMoreResultsCount: '显示更多结果({shown} / {total})',
	durationNever: '永不',
	durationDays: '{count}{unit}',
	durationSeconds: '{count}{unit}',
	durationToNever: '变为永不',
	durationToDays: '变为{count}{unit}',
	simulatorSummaryTotal: '总计',
	simulatorSummaryPotential: '潜在',
	foodInfoRecipes: '配方',
	foodInfoFrom: '来自',
	foodInfoCook: '烹饪',
	foodInfoDryIn: '{duration}晒干',
	foodInfoCannotAdd: '不能加入锅炉',
	noteProvidesHeatFor: '提供 {heat} 热量，持续 {duration}',
	noteHeatWhenConsumed: '食用时提供 {heat} 热量',
	noteLightSeconds: '提供{seconds}秒照明',
	noteSpeedBonusForSeconds: '提供{speed}点移速加成（{percent}），持续{seconds}秒',
	noteDriesRateForSeconds: '提供每秒{rate}点干燥效果，持续{seconds}秒',
	noteHeatDelta: '{heat}热量',
	noteGlowDarkMinutes: '让玩家在黑暗中发光{minutes}分钟',
	notePreventsHayfeverSeconds: '防止花粉症{seconds}秒',
	notePoisonous: '有毒',
	noteCuresPoison: '解毒',
	notePutsPlayerToSleep: '使玩家入睡',
	noteRemovesGrogginessEffect: '移除昏沉效果',
	noteGivesNaughtiness: '提供{amount}点淘气值',
	noteSpeedBonusForSecondsDays: '提供{speed}点移速加成（{percent}），持续{seconds}秒（{days}天）',
	noteHayfeverSecondsDays: '防止花粉症{seconds}秒（{days}天）',
	noteProducesAndHealsOverMinutes: '每次产出{count}份；在{minutes}分钟内恢复{health}生命值',
	noteIncreasesTemperatureByDegreesInSeconds: '在{seconds}秒内提高{degrees}度温度。',
	noteRestoresSanityOverMinutes: '在{minutes}分钟内恢复{sanity}点理智',
	noteLowersTemperatureByDegreesOverSeconds: '在{seconds}秒内降低{degrees}度温度',
	noteRaisesTemperatureByDegreesOverSeconds: '在{seconds}秒内提高{degrees}度温度',
	noteRequiresUncookedTallbirdEgg: '需要未烹饪的高脚鸟蛋',
	notePlayerCannotEatBeefaloOnly: '玩家不能食用，只能喂给皮弗娄牛',
	noteDustMothsOnly: '用于喂食尘蛾，玩家不能食用',
	notes: {
		'Removes 3 heat, and for 30 seconds, dries 1/s and adds 2 bonus speed (+33%)':
			'移除3点热量，并在30秒内提供每秒1点干燥效果和2点移速加成（+33%）',
		'While worn, restores 3.9 Hunger every 5 seconds (187.5 in total, over 4 minutes), while reducing Sanity by 1.33 per minute (Wurt gains +1.33 sanity/min, Wigfrid refuses to wear this)':
			'穿戴时每5秒恢复3.9点饥饿值（4分钟共187.5点），同时每分钟降低1.33点理智（沃特获得每分钟+1.33理智，薇格弗德拒绝佩戴）',
		'Gives those that eat this 16 minutes of light that fades in a similar fashion after eating a glowberry':
			'食用后提供16分钟照明，且会像食用发光浆果后一样逐渐减弱',
	},

	columns: '列',
	autoColumns: '自动',
	autoColumnsTitle: '在窄屏幕上自动隐藏次要列',
	tableName: '名称',
	tableInfo: '信息',
	tableMode: '模式',
	tableHealth: '生命',
	tableHealthGain: '生命+',
	tableHunger: '饥饿',
	tableHungerGain: '饥饿+',
	tableSanity: '理智',
	tablePerish: '腐败',
	tableCookTime: '烹饪时间',
	tablePriority: '优先级',
	tableNotes: '备注',
	tableRequires: '需要',
	tableIngredients: '食材',
	tableHealthHint: '恢复的生命值(烹饪后会变化)',
	tableHungerHint: '恢复的饥饿值(烹饪后会变化)',
	tableSanityHint: '恢复的理智值(烹饪后会变化)',
	tablePerishHint: '变成腐烂物所需时间(烹饪后会变化)',
	tablePriorityHint: '该组合会产出优先级最高的配方之一',
	tableRequiresHint: '变暗或带删除线的项目不可使用',
	tableModeHint: '需要对应 DLC 或游戏模式',
	tableHealthGainHint: '相较于食材获得的生命增益',
	tableHungerGainHint: '相较于食材获得的饥饿增益',

	aboutHeading: '关于本食物指南',
	aboutIntro:
		'这是一个非官方工具,帮助你在 <a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a> 中避免饿死。这是一款由 <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a> 制作的、充满科学与魔法、毫不留情的荒野生存游戏。',
	aboutBrowser:
		'本页面需要现代浏览器(较新版本的 Firefox、Chrome、Edge 或 Safari),并通过 JavaScript 在本地运行。',
	aboutSource:
		'开源,作为社区项目维护于 GitHub:<a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">github.com/bluehexagons/foodguide</a>。',
	aboutChangelog:
		'最新更改请查看 <a href="https://github.com/bluehexagons/foodguide/commits/main" target="_blank" rel="noopener">提交历史</a>。',
	aboutSectionsHeading: '各部分说明',
	aboutSimulatorHeading: '模拟器',
	aboutSimulatorBody:
		'模拟器的运作方式与锅炉相同:加入物品后会告诉你将做出何种食物。请注意,实际烹饪时只有最高优先级的配方才会成为候选。顶部的合计反映加入的食材,腐败时间取最短者。结果下方的建议显示在已加入食材的基础上再加入不同物品可制作的其他配方。',
	aboutDiscoveryHeading: '发现',
	aboutDiscoveryBody:
		'发现标签页根据一组食材查找可制作的配方。它不考虑物品数量,而是假设每种你都有四个。你也可以计算使用现有食材的高效配方,以便锅炉烹饪时获得最大的生命或饥饿收益。其工作方式与统计分析器相同,但仅限于你的背包。',
	aboutFoodRecipeListsHeading: '食物列表与配方列表',
	aboutFoodRecipeListsBody:
		"浏览所选游戏版本中可用的全部食物和锅炉配方。使用左上角的版本选择器在 Don't Starve Together、Don't Starve 和 Hamlet 之间切换。",
	aboutStatisticsHeading: '统计分析器',
	aboutStatisticsBody:
		'统计分析器标签页适合喜欢探索食材组合的玩家。它会计算所有有效的食材组合(使用"理想"食材选择,通常排除生食),并允许按配方和食材内容进行筛选。在较慢的电脑上计算可能需要一些时间。',
	aboutAdvancedHeading: '高级用法(JavaScript 全局变量)',
	aboutAdvancedBody1:
		'本食物指南会向 <code>window</code> 添加几个属性:<code>food</code>、<code>recipes</code> 和 <code>matchingNames</code>。统计分析器将其结果写入 <code>analysis</code> 和 <code>recipeCrunchData</code>。本地状态保存在 <code>localStorage.foodGuideState</code> 中。',
	aboutAdvancedBody2:
		'高级用法请打开浏览器的 JavaScript 控制台。<code>analysis.made</code> 包含上次分析中所有可行组合的列表,包括界面之外未显示的部分。',
	aboutLinksHeading: '链接',
	linkChangelog: '本指南更新日志',
	linkBugReports: '反馈本指南的错误 / 问题',
	linkOfficialSite: "Don't Starve 官方网站",
	linkWiki: "Don't Starve Wiki",

	gameInfoFoodMechHeading: '食物机制',
	gameInfoFoodMechBody:
		'<strong>腐败时间</strong>是食物变为<strong>腐烂物</strong>之前的时间。在该时间的<strong>一半</strong>处,食物会变<strong>不新鲜</strong>,只提供 <strong><span id="stalehealth"></span> 的生命</strong>和 <strong><span id="stalehunger"></span> 的饥饿</strong>,且<strong>不提供理智</strong>。食物在<strong>四分之三</strong>处<strong>变质</strong>,只提供 <strong><span id="spoiledhunger"></span> 的饥饿</strong>且<strong>不再提供生命</strong>。食用变质食物会使理智下降 <strong><span id="spoiledsanity"></span></strong>。<strong>掉在地上</strong>的食物的<strong>腐败速率</strong>为 <strong><span id="perishground"></span></strong>(<strong>冬季</strong>为 <strong><span id="perishwinter"></span></strong>,<strong>夏季</strong>为 <strong><span id="perishsummer"></span></strong>),而存放在<strong>冰箱</strong>中可将速率降至 <strong><span id="perishfridge"></span></strong>。',
	gameInfoWarmth:
		'提供<strong>取暖</strong>或<strong>降温</strong>的食物的作用类似于热能石:食用后,会在一段时间内以特定温度作为热源。在该时段内再食用其他取暖/降温食物会替换之前的效果。',
	gameInfoPriority:
		'<strong>配方优先级</strong>决定食材组合会做出哪种配方;一组食材只能产出可能的最高优先级配方。',
	gameInfoCooked: '配方需求中,通常不区分熟食与生食。如有区别,只会列出可用的形态。',
	gameInfoVersionsHeading: '游戏版本与 DLC',
	gameInfoVersionsBody:
		"左上角的游戏版本选择器可在 Don't Starve Together (DST)、Don't Starve (DS) 和 Hamlet 之间切换。选中 Don't Starve 时,可启用或禁用 Reign of Giants 和 Shipwrecked DLC,以控制显示的食物和配方。也可以选择 Warly 或 Webber 等角色,查看其专属配方和食物机制。",
	gameInfoCharactersHeading: '角色食物机制',
	gameInfoWarly:
		'<strong>Warly</strong> 是一名厨师角色,只能在 Shipwrecked、Hamlet 和 DST 中游玩。在 Shipwrecked 中,他制作配方时菜肴更具饱腹感,而生吃、晒干或简单烹饪时效果较弱。他还有其他角色无法使用的独特配方。',
	gameInfoWebber:
		'<strong>Webber</strong> 是人蛛混血角色,在所有游戏版本中均可游玩。他可以安全食用怪物食物,不会受到不良影响,并且可以将生肉视为熟肉(获得全部生命且无理智惩罚)。他也是唯一可以自然与蜘蛛结成同伴的角色。',
	gameInfoWigfrid:
		'<strong>Wigfrid</strong> 来自 Reign of Giants,在 Don\'t Starve Together 中可玩。她是一名舞台演员,只吃肉类。在 Don\'t Starve Together 中她还能吃"甜食",如太妃糖、软心豆粒糖和伏特山羊酥煎。',
	gameInfoFavoritesHeading: '最爱食物 (DST)',
	gameInfoFavoritesBody:
		"在 Don't Starve Together 中,每个角色食用其最爱食物时可额外获得 15 点饥饿值。该加成受新鲜度影响。",
	favoritesHeaderCharacter: '角色',
	favoritesHeaderFavorite: '最爱食物',
	gameInfoWikiHeading: '实用 Wiki 页面',
	wikiFood: '食物',
	wikiCooking: '烹饪',
	wikiCrockPot: '锅炉',
	wikiFarming: '农作',

	footerCopyrightLicense:
		'<a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a> &copy; <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a>。非官方食物指南,<a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">源代码</a>以 <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank" rel="noopener">Apache License 2.0</a> 协议发布。',
	footerLinks:
		'<a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">GitHub 上的源代码</a> | <a href="https://github.com/bluehexagons/foodguide/issues" target="_blank" rel="noopener">错误与功能反馈</a>',

	// Ingredient/recipe tag labels. Keys must match the English dictionary
	// in html/strings.js (and the internal data identifiers); only the
	// visible label is translated. The English `tag:KEY` search prefix is
	// preserved in the underlying link payload.
	tags: {
		fruit: '水果',
		veggie: '蔬菜',
		meat: '肉',
		egg: '蛋',
		fish: '鱼',
		magic: '魔法',
		decoration: '装饰',
		inedible: '不可食用',
		monster: '怪物食物',
		sweetener: '甜味剂',
		fat: '脂肪',
		dairy: '乳制品',
		jellyfish: '水母',
		antihistamine: '抗过敏',
		filter: '过滤',
		bug: '虫',
		bone: '骨',
		roughage: '粗纤维',
		goodies: '甜食',
		honeyed: '蜂蜜调味',
		monstermeat: '怪物肉',
	},
};

registerLocale('zh', '简体中文', dict);
