/**
 * UI strings and translation helpers for the Don't Starve Food Guide.
 *
 * Goals:
 *   - All user-facing UI text emitted from the front-end goes through `t()`,
 *     so swapping locales requires no code changes.
 *   - Translations of static HTML are driven by `data-i18n` attributes; call
 *     `applyTranslations(root)` to refresh a subtree after a locale change.
 *   - Domain-specific names (foods, recipes, character names, DLCs, etc.)
 *     are intentionally NOT covered yet — those should be sourced from the
 *     game itself rather than re-translated by hand.
 *
 * Element attribute conventions:
 *   - `data-i18n="key"`               → element.textContent = t(key)
 *   - `data-i18n-html="key"`          → element.innerHTML  = t(key)
 *     (preserves child markup such as <strong> or <span id="..."> tokens)
 *   - `data-i18n-attr-NAME="key"`     → element.setAttribute(NAME, t(key))
 *     where NAME may be e.g. `title`, `placeholder`, `aria-label`.
 *
 * Interpolation: `t('key', { name: 'Wilson' })` substitutes `{name}`
 * occurrences in the resolved string.
 */

const STORAGE_KEY = 'foodGuideLocale';

/**
 * Default English string table. New keys must be added here; locale files
 * may then provide partial overrides. Anything missing falls back to English.
 */
const defaultStrings = {
	// Theme toggle
	themeToggleToDark: '🌙',
	themeToggleToLight: '☀️',
	themeToggleTitle: 'Toggle dark/light theme',

	// Language picker
	languagePickerLabel: 'Language',
	languagePickerTitle: 'Change language',
	languageNote: 'Translations were generated by Anthropic Claude Opus and may need community review.',

	// Mode selector labels in the header
	modeLabelGame: 'Game',
	modeLabelDlc: 'DLC',
	modeLabelCharacter: 'Char',
	dlcToggleHint: 'click to toggle',
	characterToggleHint: 'click to toggle',

	// Character ability descriptions (used by mode-utils.getCharacterAbilities)
	abilityNoMonsterPenalty: 'Can safely eat Monster Foods',
	abilityRawMeatIsCooked: 'Can safely eat Raw Meat',
	abilityMeatOnly: 'Only eats meat',
	abilityMeatAndGoodies: 'Only eats meat and goodies',

	// Navbar tabs
	tabSimulator: 'Simulator',
	tabSimulatorTitle: 'Crock Pot recipe simulation',
	tabDiscovery: 'Discovery',
	tabDiscoveryTitle: 'Add inventory items to find recipes',
	tabFoodList: 'Food List',
	tabFoodListTitle: 'View all food in the selected DLC',
	tabRecipeList: 'Recipe List',
	tabRecipeListTitle: 'View all recipes for the selected DLC',
	tabStatistics: 'Statistics Analyzer',
	tabStatisticsTitle: 'Find all recipes (unstable)',
	tabAbout: 'About',
	tabAboutTitle: 'About this tool and how to use it',
	tabGameInfo: 'Game Info',
	tabGameInfoTitle: "Don't Starve game mechanics reference",

	// Top-level instructions
	noscriptMessage: 'Sorry, this Food Guide requires JavaScript and a modern web browser.',
	simulatorHeading: 'Crock Pot Simulator',
	simulatorBody:
		'Search for ingredients below, then click them to add to the pot. Click a slot to remove an ingredient.',
	discoveryHeading: 'Inventory Discovery',
	discoveryBody:
		'Add all items in your inventory below to see what recipes you can make. Click the + to add more items.',
	discoveryFoodStatsHeading: 'Stats about your food:',
	discoveryRecipesHeading: 'With these, you can make:',
	discoveryEfficientHeading: 'Find what recipes are most efficient:',
	discoveryHighlightsNote: 'The highlighted row(s) will be selected from when cooking.',
	discoveryMoreSuggestions: 'Add more ingredients to make:',
	simulatorSelectedIngredients: 'Selected crock pot ingredients',
	discoverySelectedIngredients: 'Food on hand',
	searchIngredientsPlaceholder: 'Search ingredients...',

	// Ingredient picker controls
	clearSearchOrIngredients: 'Clear search or remove all ingredients',
	confirmClearInventory: 'Are you sure you want to clear all ingredients from your inventory?',
	displayModeNames: 'Display: Names',
	displayModeIcons: 'Display: Icons',
	displayModeList: 'Display: List',
	sortDefault: 'Sort: Default',
	sortName: 'Sort: Name',
	sortHealth: 'Sort: Health',
	sortHunger: 'Sort: Hunger',
	sortSanity: 'Sort: Sanity',
	sortPerish: 'Sort: Perish',
	searchTypeName: 'name',
	searchTypeTag: 'tag',
	searchTypeRecipe: 'recipe',
	searchPlaceholderName: 'Filter ingredients',
	searchPlaceholderTag: 'Meat, veggie, fruit, egg, monster...',
	searchPlaceholderRecipe: 'Find ingredients used in a recipe',

	// Statistics analyzer ("recipe grinder")
	calculateRecipes: 'Calculate efficient recipes (may take some time)',
	clearResults: 'Clear results',
	calculating: 'Calculating...',
	pause: 'Pause',
	resume: 'Resume',
	computingCombinations: 'Computing combinations..',
	multipleResultsNote: '* combination has multiple possible results',
	filterCycleHelp:
		'Click ingredients/recipes to cycle: normal → required (✓) → excluded (✕). Right-click for quick exclude.',
	customFilterPlaceholder: 'use custom filter',
	foundValidRecipes: 'Found {count} valid recipes.',
	foundValidRecipesInProgress:
		'Found {count} valid recipes.. (you can change Food Guide tabs during this process)',
	foundValidRecipesPaused: 'Found {count} valid recipes (paused)',
	showMoreResults: 'Show more results',
	showMoreResultsCount: 'Show more results ({shown} of {total})',
	durationNever: 'Never',
	durationDays: '{count} {unit}',
	durationSeconds: '{count} {unit}',
	durationToNever: 'to Never',
	durationToDays: 'to {count} {unit}',
	foodInfoRecipes: 'Recipes',
	foodInfoFrom: 'from',
	foodInfoCook: 'cook',
	foodInfoDryIn: 'dry in {duration}',
	foodInfoCannotAdd: 'cannot be added to crock pot',
	noteProvidesHeatFor: 'Provides {heat} heat for {duration}',
	noteHeatWhenConsumed: '{heat} heat when consumed',
	noteLightSeconds: 'Gives {seconds} seconds of light',
	noteSpeedBonusForSeconds: 'Gives {speed} bonus speed ({percent}) for {seconds} seconds',
	noteDriesRateForSeconds: 'Dries {rate} for {seconds} seconds',
	noteHeatDelta: '{heat} heat',
	noteGlowDarkMinutes: 'Makes the player glow in the dark for {minutes} minutes',
	notePreventsHayfeverSeconds: 'Prevents hayfever for {seconds} seconds',
	notePoisonous: 'Poisonous',
	noteCuresPoison: 'Cures poison',
	notePutsPlayerToSleep: 'Puts the player to sleep',
	noteRemovesGrogginessEffect: 'Removes grogginess effect',
	noteGivesNaughtiness: 'Gives {amount} naughtiness',
	noteSpeedBonusForSecondsDays:
		'Gives {speed} bonus speed ({percent}) for {seconds} seconds ({days} days)',
	noteHayfeverSecondsDays: 'Prevents hayfever for {seconds} seconds ({days} days)',
	noteProducesAndHealsOverMinutes:
		'Recipe produces {count}; heals {health} health over {minutes} minutes',
	noteIncreasesTemperatureByDegreesInSeconds:
		'Increases temperature by {degrees} degrees in {seconds} seconds.',
	noteRestoresSanityOverMinutes: 'Restores {sanity} sanity over {minutes} minutes',
	noteLowersTemperatureByDegreesOverSeconds:
		'Lowers temperature by {degrees} degrees over {seconds} seconds',
	noteRaisesTemperatureByDegreesOverSeconds:
		'Raises temperature by {degrees} degrees over {seconds} seconds',
	noteRequiresUncookedTallbirdEgg: 'Requires uncooked Tallbird Egg',
	notePlayerCannotEatBeefaloOnly: 'Cannot be eaten by the player, only given to Beefalo',
	noteDustMothsOnly: 'Used to feed Dust Moths, cannot be eaten by the player',

	/*
	 * One-off note text still attached directly to food/recipe entries.
	 * Keys are the canonical English note strings from food.js / recipes.js.
	 * Locale files may override any subset under `notes: { ... }`.
	 * Repeated note patterns should prefer stable `noteKey` templates above.
	 */
	notes: {
		'Removes 3 heat, and for 30 seconds, dries 1/s and adds 2 bonus speed (+33%)':
			'Removes 3 heat, and for 30 seconds, dries 1/s and adds 2 bonus speed (+33%)',
		'While worn, restores 3.9 Hunger every 5 seconds (187.5 in total, over 4 minutes), while reducing Sanity by 1.33 per minute (Wurt gains +1.33 sanity/min, Wigfrid refuses to wear this)':
			'While worn, restores 3.9 Hunger every 5 seconds (187.5 in total, over 4 minutes), while reducing Sanity by 1.33 per minute (Wurt gains +1.33 sanity/min, Wigfrid refuses to wear this)',
		'Gives those that eat this 16 minutes of light that fades in a similar fashion after eating a glowberry':
			'Gives those that eat this 16 minutes of light that fades in a similar fashion after eating a glowberry',
	},

	// Table column-toggle controls
	columns: 'Columns',
	autoColumns: 'Auto',
	autoColumnsTitle: 'Automatically hide less-important columns on narrow screens',
	tableName: 'Name',
	tableInfo: 'Info',
	tableMode: 'Mode',
	tableHealth: 'Health',
	tableHealthGain: 'Health+',
	tableHunger: 'Hunger',
	tableHungerGain: 'Hunger+',
	tableSanity: 'Sanity',
	tablePerish: 'Perish',
	tableCookTime: 'Cook Time',
	tablePriority: 'Priority',
	tableNotes: 'Notes',
	tableRequires: 'Requires',
	tableIngredients: 'Ingredients',
	tableHealthHint: 'Health restored (change if cooked)',
	tableHungerHint: 'Hunger restored (change if cooked)',
	tableSanityHint: 'Sanity restored (change if cooked)',
	tablePerishHint: 'Time to turn to rot (change if cooked)',
	tablePriorityHint: 'One of the highest priority recipes for a combination will be made',
	tableRequiresHint: 'Dim, struck items cannot be used',
	tableModeHint: 'DLC or Game Mode required',
	tableHealthGainHint: 'Health gained compared to ingredients',
	tableHungerGainHint: 'Hunger gained compared to ingredients',

	// About page
	aboutHeading: 'About This Food Guide',
	aboutIntro:
		'This is an unofficial tool to help avoid starvation in <a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a>, an uncompromising wilderness survival game full of science and magic by <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a>.',
	aboutBrowser:
		'This page requires a modern web browser, such as a recent version of Firefox, Chrome, Edge, or Safari, and runs locally using JavaScript.',
	aboutSource:
		'Open-source and maintained as a community effort on GitHub: <a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">github.com/bluehexagons/foodguide</a>.',
	aboutChangelog:
		'For the latest changes, see the <a href="https://github.com/bluehexagons/foodguide/commits/main" target="_blank" rel="noopener">commit history</a>.',
	aboutSectionsHeading: 'Sections',
	aboutSimulatorHeading: 'Simulator',
	aboutSimulatorBody:
		'The Simulator works like a Crock Pot: add items, and it will tell you what food will be prepared. Note that only the highest-priority recipes will be candidates when actually cooking in-game. The combined totals at the top reflect the ingredients added, where perish time is the shortest. The suggestions below the real results show what recipes could be made by adding different items to those already in the Crock Pot.',
	aboutDiscoveryHeading: 'Discovery',
	aboutDiscoveryBody:
		"The Discovery tab finds what recipes can be prepared using a collection of ingredients. It doesn't take item quantity into account, instead assuming you have four of each. You are also able to calculate efficient recipes using your ingredients to get the most health or hunger benefit from cooking them in the crock pot. This works identically to the Statistics Analyzer tab, but limited to your inventory.",
	aboutFoodRecipeListsHeading: 'Food List & Recipe List',
	aboutFoodRecipeListsBody:
		"Browse all foods and Crock Pot recipes available in the selected game version. Use the version selector in the upper-left to switch between Don't Starve Together, Don't Starve, and Hamlet.",
	aboutStatisticsHeading: 'Statistics Analyzer',
	aboutStatisticsBody:
		'The Statistics Analyzer tab is for those who just want to explore ingredient combinations. It will calculate every valid ingredient combination possible (using an "ideal" ingredient selection, generally excluding uncooked food) and allows filtration by recipe and ingredient contents. Computation may take some time on slower computers.',
	aboutAdvancedHeading: 'Advanced Use (JavaScript Globals)',
	aboutAdvancedBody1:
		'The Food Guide populates <code>window</code> with a few properties: <code>food</code>, <code>recipes</code>, and <code>matchingNames</code>. The Statistics Analyzer writes its results to <code>analysis</code> and <code>recipeCrunchData</code>. The local state is stored under <code>localStorage.foodGuideState</code>.',
	aboutAdvancedBody2:
		"For advanced use, open your browser's JavaScript console. <code>analysis.made</code> contains the list of the working combinations from the last analysis, including beyond those visible in the interface.",
	aboutLinksHeading: 'Links',
	linkChangelog: 'Food Guide Changelog',
	linkBugReports: 'Report Food Guide Bugs / Issues',
	linkOfficialSite: "Don't Starve Official Website",
	linkWiki: "Don't Starve Wiki",

	// Game Info page
	gameInfoFoodMechHeading: 'Food Mechanics',
	gameInfoFoodMechBody:
		'<strong>Perish time</strong> is the time before a food item becomes <strong>Rot</strong>. <strong>Halfway</strong> through this period, it will go <strong>stale</strong>, and give <strong><span id="stalehealth"></span> health</strong> and <strong><span id="stalehunger"></span> hunger</strong>, as well as <strong>no sanity</strong>. Food <strong>spoils</strong> at <strong>three quarters</strong>, giving only <strong><span id="spoiledhunger"></span> hunger</strong> and <strong>no longer giving any health</strong>. Eating spoiled food will decrease sanity by <strong><span id="spoiledsanity"></span></strong>. Food <strong>dropped on the ground</strong> will <strong>perish</strong> at a rate of <strong><span id="perishground"></span></strong> (or <strong><span id="perishwinter"></span></strong> in <strong>Winter</strong>, <strong><span id="perishsummer"></span></strong> in <strong>Summer</strong>), while keeping it in the <strong>Ice Box</strong> will reduce the rate to <strong><span id="perishfridge"></span></strong>.',
	gameInfoWarmth:
		'Foods that provide <strong>warmth</strong> or <strong>cooling</strong> work like a thermal stone; when eaten, they provide a heat source at a particular temperature for a period of time. Eating another heating/cooling food within this period will replace the earlier effect.',
	gameInfoPriority:
		'<strong>Recipe priority</strong> determines which recipe a food combination will make; only the highest-priority possible recipes can be produced by a batch of ingredients.',
	gameInfoCooked:
		"In recipe requirements, cooked/uncooked usually doesn't make a difference. If it does, then only the valid form will be listed.",
	gameInfoVersionsHeading: 'Game Versions and DLC',
	gameInfoVersionsBody:
		"The game version selector in the upper-left lets you switch between Don't Starve Together (DST), Don't Starve (DS), and Hamlet. When Don't Starve is selected, you can toggle the Reign of Giants and Shipwrecked DLC on or off to control which foods and recipes are shown. You can also select a character like Warly or Webber to see their special recipes and food mechanics.",
	gameInfoCharactersHeading: 'Character Food Mechanics',
	gameInfoWarly:
		'<strong>Warly</strong> is a chef character who can only be played in Shipwrecked, Hamlet, and DST. In Shipwrecked, his meals are more filling when prepared as recipes but less effective when eaten raw, dried, or cooked. He also has access to unique recipes not available to other characters.',
	gameInfoWebber:
		'<strong>Webber</strong> is a spider-human hybrid who can be played in all game versions. He can safely eat Monster Foods without any adverse health effects, and can eat Raw Meat as if it were cooked (with full health and no sanity penalty). He is also the only character who can naturally befriend Spiders.',
	gameInfoWigfrid:
		'<strong>Wigfrid</strong> is a character from Reign of Giants available in Don\'t Starve Together. She is a stage performer who only eats meat. In Don\'t Starve Together, she can also eat "goodies" such as Taffy, Jellybeans, and Volt Goat Chaud-Froid.',
	gameInfoFavoritesHeading: 'Favorite Foods (DST)',
	gameInfoFavoritesBody:
		'In Don\'t Starve Together, each character gains an extra 15 Hunger when eating their favorite food. This bonus is affected by freshness.',
	favoritesHeaderCharacter: 'Character',
	favoritesHeaderFavorite: 'Favorite Food',
	gameInfoWikiHeading: 'Useful Wiki Pages',
	wikiFood: 'Food',
	wikiCooking: 'Cooking',
	wikiCrockPot: 'Crock Pot',
	wikiFarming: 'Farming',

	// Footer
	footerCopyrightLicense:
		'<a href="https://www.klei.com/games/dont-starve" target="_blank" rel="noopener">Don\'t Starve</a> &copy; <a href="https://klei.com/" target="_blank" rel="noopener">Klei Entertainment</a>. Unofficial food guide <a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">source code</a> made available under the <a href="https://www.apache.org/licenses/LICENSE-2.0" target="_blank" rel="noopener">Apache License 2.0</a>.',
	footerLinks:
		'<a href="https://github.com/bluehexagons/foodguide" target="_blank" rel="noopener">Source Code on GitHub</a> | <a href="https://github.com/bluehexagons/foodguide/issues" target="_blank" rel="noopener">Bugs and Feature Reports</a>',

	/*
	 * Ingredient/recipe tag labels.
	 *
	 * Keys here are the *internal* tag identifiers used throughout the
	 * data files (e.g. food.js properties, recipe `tags: [...]` entries,
	 * `foodtype` strings). They are **input syntax** for the tag-search
	 * (e.g. `tag:meat`) and must stay in English in URLs / dataset.link
	 * payloads. Only the *visible* label is translated.
	 *
	 * Locale files may override any subset under `tags: { ... }`; missing
	 * keys fall back to the English label here, then to the raw key. To
	 * add a new tag, register it here first so contributors can mirror
	 * the entry in each `html/locales/*.js`.
	 *
	 * Includes:
	 *   - ingredient tags shown as chips on each food (fruit, meat, ...)
	 *   - foodtype categories (meat, veggie, goodies)
	 *   - recipe metadata tags (honeyed, monstermeat)
	 */
	tags: {
		// Ingredient tags (shown on each food row as clickable chips)
		fruit: 'fruit',
		veggie: 'vegetable',
		meat: 'meat',
		egg: 'egg',
		fish: 'fish',
		magic: 'magic',
		decoration: 'decoration',
		inedible: 'inedible',
		monster: 'monster food',
		sweetener: 'sweetener',
		fat: 'fat',
		dairy: 'dairy',
		jellyfish: 'jellyfish',
		antihistamine: 'antihistamine',
		filter: 'filter',
		bug: 'bug',
		bone: 'bone',
		roughage: 'roughage',

		// Foodtype categories (recipe.foodtype)
		goodies: 'goodies',

		// Recipe metadata tags (recipe.tags entries)
		honeyed: 'honeyed',
		monstermeat: 'monster meat',
	},
};

/** @typedef {Partial<typeof defaultStrings>} LocaleDict */

/**
 * Metadata about a registered locale: the display name (in its own
 * language) and the partial dictionary of translations.
 * @typedef {{ name: string, dict: LocaleDict, dir?: 'ltr' | 'rtl' }} LocaleEntry
 */

/** @type {Record<string, LocaleEntry>} */
const locales = {
	en: { name: 'English', dict: defaultStrings },
};

let activeLocale = 'en';

/**
 * Register a translation dictionary. Missing keys fall back to English.
 * @param {string} code - BCP-47-style language tag (e.g. "es", "zh", "pt-BR").
 * @param {string} name - Display name in the locale's own language.
 * @param {LocaleDict} dict - Partial overrides keyed by string id.
 * @param {{ dir?: 'ltr' | 'rtl' }} [opts]
 */
export function registerLocale(code, name, dict, opts) {
	const dir = opts && opts.dir === 'rtl' ? 'rtl' : 'ltr';
	locales[code] = { name, dict, dir };
}

/**
 * Returns the BCP-47-style codes of all registered locales (always
 * includes 'en').
 * @returns {string[]}
 */
export function listLocales() {
	return Object.keys(locales);
}

/**
 * Display name of the registered locale (in that locale's own language),
 * or the code itself if unknown.
 * @param {string} code
 */
export function localeName(code) {
	return locales[code] ? locales[code].name : code;
}

/**
 * Currently active locale code.
 */
export function getLocale() {
	return activeLocale;
}

/**
 * Switch the active locale. Unknown codes silently fall back to English.
 * Persists the choice to localStorage and dispatches a `foodguide:localechange`
 * event on `document` so listeners can refresh.
 * @param {string} code
 */
export function setLocale(code) {
	if (!locales[code]) return;
	activeLocale = code;
	if (typeof document !== 'undefined') {
		const html = document.documentElement;
		html.setAttribute('lang', code);
		html.setAttribute('dir', locales[code].dir === 'rtl' ? 'rtl' : 'ltr');
		try {
			localStorage.setItem(STORAGE_KEY, code);
		} catch {
			/* ignore quota / unavailable storage */
		}
		document.dispatchEvent(new CustomEvent('foodguide:localechange', { detail: { code } }));
	}
}

/**
 * Initialise the locale: read from localStorage if set, otherwise
 * pick the first registered locale that matches `navigator.language`,
 * otherwise English. Safe to call before `applyTranslations`.
 */
export function initLocale() {
	if (typeof document === 'undefined') return;
	let code;
	try {
		code = localStorage.getItem(STORAGE_KEY);
	} catch {
		/* ignore */
	}
	if (!code && typeof navigator !== 'undefined' && navigator.language) {
		const nav = navigator.language.toLowerCase();
		const candidates = [nav, nav.split('-')[0]];
		for (const c of candidates) {
			if (locales[c]) {
				code = c;
				break;
			}
		}
	}
	if (code && locales[code]) {
		setLocale(code);
	} else {
		setLocale('en');
	}
}

/**
 * Read a translated string by key, with optional `{name}` interpolation.
 * @param {keyof typeof defaultStrings} key
 * @param {Record<string, string | number>} [params]
 * @returns {string}
 */
export function t(key, params) {
	const entry = locales[activeLocale];
	let value;
	if (entry && entry.dict && /** @type {any} */ (entry.dict)[key] !== undefined) {
		value = /** @type {any} */ (entry.dict)[key];
	} else {
		value = /** @type {any} */ (defaultStrings)[key];
	}
	if (value === undefined) return String(key);
	if (params) {
		return String(value).replace(/\{(\w+)\}/g, (_, name) =>
			Object.prototype.hasOwnProperty.call(params, name) ? String(params[name]) : `{${name}}`,
		);
	}
	return value;
}

export function durationUnit(kind, count) {
	if (kind === 'day') {
		if (activeLocale === 'zh') return '天';
		if (activeLocale === 'es') return count === 1 ? 'dia' : 'dias';
		return count === 1 ? 'day' : 'days';
	}
	if (kind === 'sec') {
		if (activeLocale === 'zh') return '秒';
		if (activeLocale === 'es') return count === 1 ? 'seg' : 'segs';
		return count === 1 ? 'sec' : 'secs';
	}
	return kind;
}

export function formatDuration(kind, count) {
	if (kind === 'day') {
		return t('durationDays', { count, unit: durationUnit('day', count) });
	}
	if (kind === 'sec') {
		return t('durationSeconds', { count, unit: durationUnit('sec', count) });
	}
	return String(count);
}

/**
 * Resolve a localized label for an internal tag identifier.
 *
 * Lookup order:
 *   1. `tags[key]` in the active locale's dictionary
 *   2. `tags[key]` in the default (English) dictionary
 *   3. the supplied `fallback`
 *   4. the raw `key` itself
 *
 * The returned string is intended for display only; the original `key`
 * should still be used wherever the tag identifier is part of input
 * syntax (e.g. `tag:KEY` search queries or `dataset.link` payloads).
 *
 * @param {string} key - Internal tag identifier (e.g. 'meat', 'honeyed').
 * @param {string} [fallback] - Optional fallback label if no entry exists.
 * @returns {string}
 */
export function tagLabel(key, fallback) {
	const entry = locales[activeLocale];
	const localeTags = entry && entry.dict && /** @type {any} */ (entry.dict).tags;
	if (localeTags && Object.prototype.hasOwnProperty.call(localeTags, key)) {
		return localeTags[key];
	}
	const defaultTags = /** @type {any} */ (defaultStrings).tags;
	if (defaultTags && Object.prototype.hasOwnProperty.call(defaultTags, key)) {
		return defaultTags[key];
	}
	return fallback !== undefined ? fallback : key;
}

/**
 * Resolve a localized one-off note string from its canonical English source text.
 *
 * Lookup order:
 *   1. `notes[note]` in the active locale dictionary
 *   2. `notes[note]` in the default English dictionary
 *   3. the original `note`
 *
 * @param {string} note
 * @returns {string}
 */
export function noteText(note) {
	const entry = locales[activeLocale];
	const localeNotes = entry && entry.dict && /** @type {any} */ (entry.dict).notes;
	if (localeNotes && Object.prototype.hasOwnProperty.call(localeNotes, note)) {
		return localeNotes[note];
	}
	const defaultNotes = /** @type {any} */ (defaultStrings).notes;
	if (defaultNotes && Object.prototype.hasOwnProperty.call(defaultNotes, note)) {
		return defaultNotes[note];
	}
	return note;
}

/**
 * Resolve a note from a stable translation key, falling back to noteText for
 * one-off exact-string notes when no key is provided.
 *
 * @param {string | undefined} noteKey
 * @param {Record<string, string | number>} [params]
 * @param {string} [fallbackNote]
 * @returns {string}
 */
export function resolveNote(noteKey, params, fallbackNote) {
	if (noteKey) {
		return t(noteKey, params);
	}
	return fallbackNote ? noteText(fallbackNote) : '';
}

/**
 * Walk a DOM subtree and apply translations to elements carrying
 * `data-i18n*` attributes. Safe to call repeatedly.
 * @param {ParentNode} [root=document]
 */
export function applyTranslations(root) {
	if (typeof document === 'undefined') return;
	const scope = root || document;
	const nodes = [];
	if (scope instanceof Element) {
		nodes.push(scope);
	}
	nodes.push(...Array.from(scope.querySelectorAll('*')));

	for (const el of nodes) {
		if (el.hasAttribute('data-i18n')) {
			el.textContent = t(/** @type {any} */ (el.getAttribute('data-i18n')));
		}
	}
	for (const el of nodes) {
		if (el.hasAttribute('data-i18n-html')) {
			el.innerHTML = t(/** @type {any} */ (el.getAttribute('data-i18n-html')));
		}
	}
	for (const el of nodes) {
		for (const attr of Array.from(el.attributes)) {
			if (attr.name.startsWith('data-i18n-attr-')) {
				const target = attr.name.slice('data-i18n-attr-'.length);
				el.setAttribute(target, t(/** @type {any} */ (attr.value)));
			}
		}
	}
}

/**
 * The full English string table; useful as a base for new locale dicts.
 */
export const strings = defaultStrings;
