name: CI

permissions:
    contents: read

on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    check:
        uses: ./.github/workflows/check.yml
        permissions:
            contents: read
